[package]
description = "The fast, collaborative code editor."
edition.workspace = true
name = "sarnet"
version = "1.6.0"
publish.workspace = true
license = "GPL-3.0-or-later"
authors = ["Zed Team <hi@zed.dev>"]
default-run = "sarnet"

[lints]
workspace = true

[features]
tracy = ["ztracing/tracy"]
track-project-leak = ["gpui/leak-detection"]
test-support = [
    "gpui/test-support",
    "gpui_platform/screen-capture",
    "workspace/test-support",
    "project/test-support",
    "terminal_view/test-support",
    "title_bar/test-support",
]

[[bin]]
name = "sarnet"
path = "src/main.rs"

[dependencies]
activity_indicator.workspace = true
anyhow.workspace = true
askpass.workspace = true
assets.workspace = true
auto_update.workspace = true
auto_update_ui.workspace = true
breadcrumbs.workspace = true
chrono.workspace = true
clap.workspace = true
cli.workspace = true
client.workspace = true
collections.workspace = true
command_palette.workspace = true
crashes.workspace = true
db.workspace = true
diagnostics.workspace = true
editor.workspace = true
env_logger.workspace = true
feature_flags.workspace = true
fs.workspace = true
futures.workspace = true
go_to_line.workspace = true
gpui = { workspace = true, features = ["input-latency-histogram"] }
gpui_platform = {workspace = true, features=["screen-capture", "font-kit", "wayland", "x11"]}
gpui_tokio.workspace = true
http_client.workspace = true
install_cli.workspace = true
json_schema_store.workspace = true
keymap_editor.workspace = true
language.workspace = true
log.workspace = true
markdown.workspace = true
node_runtime.workspace = true
menu.workspace = true
migrator.workspace = true
mimalloc = { version = "0.1", optional = true }
outline.workspace = true
parking_lot.workspace = true
paths.workspace = true
picker.workspace = true
profiling.workspace = true
project.workspace = true
project_panel.workspace = true
proto.workspace = true
rayon.workspace = true
release_channel.workspace = true
remote.workspace = true
reqwest.workspace = true
recent_projects.workspace = true
reqwest_client.workspace = true
rope.workspace = true
search.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
session.workspace = true
settings.workspace = true
shellexpand.workspace = true
smol.workspace = true
sysinfo.workspace = true
system_specs.workspace = true
tab_switcher.workspace = true
task.workspace = true
tasks_ui.workspace = true
telemetry.workspace = true
telemetry_events.workspace = true
terminal_view.workspace = true
theme.workspace = true
theme_settings.workspace = true
time.workspace = true
time_format.workspace = true
title_bar.workspace = true
tracing.workspace = true
ui.workspace = true
ui_prompt.workspace = true
url.workspace = true
urlencoding.workspace = true
util.workspace = true
uuid.workspace = true
vim.workspace = true
vim_mode_setting.workspace = true
watch.workspace = true
workspace.workspace = true
zed_actions.workspace = true
zed_env_vars.workspace = true
zlog.workspace = true
zlog_settings.workspace = true
ztracing.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
etw_tracing.workspace = true
windows.workspace = true
gpui = { workspace = true, features = [
    "input-latency-histogram",
    "windows-manifest",
] }

[build-dependencies]
windows_resources = { path = "../windows_resources" }

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
gpui = { workspace = true, features = [
    "input-latency-histogram",
    "wayland",
    "x11",
] }
ashpd.workspace = true
image.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.build-dependencies]
image.workspace = true

[target.'cfg(target_os = "linux")'.build-dependencies]
pkg-config = "0.3.22"

[dev-dependencies]
gpui = { workspace = true, features = ["input-latency-histogram", "test-support"] }
project_panel = { workspace = true }
project = { workspace = true, features = ["test-support"] }
terminal_view = { workspace = true, features = ["test-support"] }
workspace = { workspace = true, features = ["test-support"] }

[package.metadata.bundle-dev]
icon = ["resources/app-icon-dev@2x.png", "resources/app-icon-dev.png"]
identifier = "dev.sarnet.Sarnet-Dev"
name = "Sarnet Dev"
osx_minimum_system_version = "10.15.7"
osx_info_plist_exts = ["resources/info/*"]
osx_url_schemes = ["sarnet"]

[package.metadata.bundle-nightly]
icon = ["resources/app-icon-nightly@2x.png", "resources/app-icon-nightly.png"]
identifier = "dev.sarnet.Sarnet-Nightly"
name = "Sarnet Nightly"
osx_minimum_system_version = "10.15.7"
osx_info_plist_exts = ["resources/info/*"]
osx_url_schemes = ["sarnet"]

[package.metadata.bundle-preview]
icon = ["resources/app-icon-preview@2x.png", "resources/app-icon-preview.png"]
identifier = "dev.sarnet.Sarnet-Preview"
name = "Sarnet Preview"
osx_minimum_system_version = "10.15.7"
osx_info_plist_exts = ["resources/info/*"]
osx_url_schemes = ["sarnet"]

[package.metadata.bundle-stable]
icon = ["resources/app-icon@2x.png", "resources/app-icon.png"]
identifier = "dev.sarnet.Sarnet"
name = "Sarnet"
osx_minimum_system_version = "10.15.7"
osx_info_plist_exts = ["resources/info/*"]
osx_url_schemes = ["sarnet"]

[package.metadata.cargo-machete]
ignored = ["profiling", "zstd", "tracing"]
